<?php
require_once __DIR__ . '/includes/db.php';
$assetBase = '';
$pageTitle = 'Register';
require_once __DIR__ . '/includes/header.php';

// Fetch activities dynamically from MySQL for the checkboxes / multi-select.
// IMPORTANT (rubric): activity options are generated by this PHP loop —
// never hardcode <option> or <input type=checkbox> tags for activity names.
$cc_result = $conn->query("SELECT activity_id, activity_name, category
                            FROM activities WHERE activity_type = 'Co-Curricular'
                            ORDER BY category, activity_name");
$ec_result = $conn->query("SELECT activity_id, activity_name, category
                            FROM activities WHERE activity_type = 'Extra-Curricular'
                            ORDER BY category, activity_name");

// Fetch colleges for the dropdown (also DB-driven, not hardcoded)
$college_result = $conn->query("SELECT college_id, college_name, city, state FROM colleges ORDER BY college_name");
?>

<section class="section">
  <div class="container">
    <h1 class="section-title">Student Registration</h1>
    <p class="section-sub">Fill in your details once and pick as many activities as you like.</p>

    <div class="card">
      <div id="server-alert">
        <?php if (!empty($_SESSION['reg_error'])): ?>
          <div class="alert alert-error"><?php echo htmlspecialchars($_SESSION['reg_error']); ?></div>
          <?php unset($_SESSION['reg_error']); ?>
        <?php endif; ?>
      </div>

      <form id="registrationForm" action="register_process.php" method="POST"
            enctype="multipart/form-data" novalidate>

        <div class="form-grid">
          <div class="field full">
            <label for="name">Full Name *</label>
            <input type="text" id="name" name="name" required>
            <div class="error-msg" data-error-for="name"></div>
          </div>

          <div class="field">
            <label for="roll_no">Roll Number / Student ID *</label>
            <input type="text" id="roll_no" name="roll_no" required>
            <div class="error-msg" data-error-for="roll_no"></div>
          </div>

          <div class="field">
            <label for="email">Email ID *</label>
            <input type="email" id="email" name="email" required>
            <div class="error-msg" data-error-for="email"></div>
          </div>

          <div class="field">
            <label for="mobile">Mobile Number *</label>
            <input type="tel" id="mobile" name="mobile" maxlength="10" placeholder="10-digit number" required>
            <div class="error-msg" data-error-for="mobile"></div>
          </div>

          <div class="field">
            <label for="gender">Gender (optional)</label>
            <select id="gender" name="gender">
              <option value="Prefer not to say">Prefer not to say</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
          </div>

          <div class="field full">
            <label for="college_id">College / University Name *</label>
            <select id="college_id" name="college_id" required>
              <option value="">-- Select your college --</option>
              <?php if ($college_result): while ($col = $college_result->fetch_assoc()): ?>
                <option value="<?php echo (int)$col['college_id']; ?>">
                  <?php echo htmlspecialchars($col['college_name']); ?> (<?php echo htmlspecialchars($col['city']); ?>, <?php echo htmlspecialchars($col['state']); ?>)
                </option>
              <?php endwhile; endif; ?>
              <option value="__new__">My college is not listed — add it below</option>
            </select>
            <div class="error-msg" data-error-for="college_id"></div>
          </div>

          <div class="field">
            <label for="new_college_name">New College Name</label>
            <input type="text" id="new_college_name" name="new_college_name" placeholder="Only if not listed above">
          </div>
          <div class="field">
            <label for="new_city">City / State</label>
            <input type="text" id="new_city" name="new_city" placeholder="e.g. Katihar, Bihar">
          </div>

          <div class="field">
            <label for="course">Course *</label>
            <input type="text" id="course" name="course" placeholder="e.g. B.Tech CSE" required>
            <div class="error-msg" data-error-for="course"></div>
          </div>

          <div class="field">
            <label for="year_sem">Year / Semester *</label>
            <input type="text" id="year_sem" name="year_sem" placeholder="e.g. 3rd Year / 5th Sem" required>
            <div class="error-msg" data-error-for="year_sem"></div>
          </div>

          <div class="field">
            <label for="password">Create Password *</label>
            <input type="password" id="password" name="password" minlength="6" required>
            <div class="error-msg" data-error-for="password"></div>
          </div>

          <div class="field">
            <label for="id_card">Upload College ID Card (optional)</label>
            <input type="file" id="id_card" name="id_card" accept=".jpg,.jpeg,.png,.pdf">
          </div>

          <div class="field full">
            <fieldset class="activity-fieldset">
              <legend>Co-Curricular Activities (select any number)</legend>
              <div class="checkbox-grid">
                <?php if ($cc_result): while ($a = $cc_result->fetch_assoc()): ?>
                  <label>
                    <input type="checkbox" name="cc_activities[]" value="<?php echo htmlspecialchars($a['activity_id']); ?>">
                    <?php echo htmlspecialchars($a['activity_name']); ?>
                    <span style="color:#8a8298;font-size:0.75rem;">(<?php echo htmlspecialchars($a['category']); ?>)</span>
                  </label>
                <?php endwhile; else: ?>
                  <p>No Co-Curricular activities found in the database yet.</p>
                <?php endif; ?>
              </div>
            </fieldset>
          </div>

          <div class="field full">
            <label for="ec_activities">Extra-Curricular Activities (Ctrl/Cmd-click to select multiple)</label>
            <select id="ec_activities" name="ec_activities[]" multiple>
              <?php if ($ec_result): while ($a = $ec_result->fetch_assoc()): ?>
                <option value="<?php echo htmlspecialchars($a['activity_id']); ?>">
                  <?php echo htmlspecialchars($a['activity_name']); ?> (<?php echo htmlspecialchars($a['category']); ?>)
                </option>
              <?php endwhile; else: ?>
                <option disabled>No Extra-Curricular activities found in the database yet.</option>
              <?php endif; ?>
            </select>
            <div class="error-msg" data-error-for="activities"></div>
          </div>

          <div class="field full">
            <label class="terms-row">
              <input type="checkbox" id="terms" name="terms" required>
              <span>I confirm the details above are correct and I agree to the event
                Terms &amp; Conditions. *</span>
            </label>
            <div class="error-msg" data-error-for="terms"></div>
          </div>
        </div>

        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Submit Registration</button>
        </div>
      </form>
    </div>
  </div>
</section>

<script src="js/validation.js"></script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
